apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}
data:
  ENV: "{{.Values.env}}"
  DB_PORT:  "{{.Values.variables.port}}"
  DB_HOST: "{{.Values.variables.host}}"
  DB_DATA: "{{.Values.variables.data}}"
  DB_PASSWORD: "{{.Values.variables.password}}"
  DB_USER: "{{.Values.variables.user}}"
  SECRET_KEY: "{{.Values.variables.secret}}"
